# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment_for_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_subject', models.CharField(blank=True, default='', max_length=255)),
                ('movie_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_comment', models.TextField(blank=True, default='')),
                ('user_mail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(blank=True, max_length=255)),
                ('video_type', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('video_img', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('video_file', models.FileField(upload_to='Videos')),
                ('video_rate', models.FloatField(default=0, max_length=5.0)),
                ('upload_time', models.DateTimeField()),
                ('video_year', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
